const nombres = [
    "Aguilar Mabel",
    "Alegre Daiana",
    "Andres Carme",
    "Argeles Sara",
    "Arguero Marcela",
    "Arias Carolina",
    "Barrera Lucia",
    "Bartolini Florencia",
    "Battan Marta",
    "Bernandez Marisol",
    "Blanco Daniel",
    "Blanco Liliana",
    "Blanco Hähn Valentina",
    "Blanco Hähn Pilar",
    "Blanco Hähn Delfina",
    "Blanco Hähn Felicitas",
    "Buet Victoria",
    "Cid Gladys",
    "Cid Monica",
    "Cid Aguilar Noelia",
    "D`alessandro Gisela",
    "Darcy Luciano",
    "De Marco Agostina",
    "Decoud Lourdes",
    "Dettano Andrea",
    "Diaz Adriana",
    "Ducau Nestor",
    "Erlich Luciano",
    "Fernandez Alfredo",
    "Ferrari Eugenio",
    "Frisone Santiago",
    "Fuentes Laura",
    "Galacho Alejandro",
    "Garcia Oscar",
    "Gicovate Sol",
    "Giordano Juan Pablo",
    "Gisfredi Camila",
    "Goldwasser Lucila",
    "Gomez Marti Cristian",
    "Green Veronica",
    "Grünblatt Mariano",
    "Guaragna Nicolas",
    "Haedo Lujan",
    "Hähn Karina",
    "Hargain Martin",
    "Janeiro Federico",
    "Janeiro Alberto",
    "Janeiro Martin",
    "Janeiro Maria Laura",
    "Janeiro Haedo Manuel",
    "Juarez Antonella",
    "Kaplan Tamara",
    "Kaplan Mariano",
    "Lanfranchi Juan Ignacio",
    "Leone Justina",
    "Leoni Carlos",
    "Llamgochian Florencia",
    "Loray Ana Laura",
    "Loray Luis",
    "Loray Pedro",
    "Loray Gaston",
    "Loray Aurora",
    "Loray Laura",
    "Luperini Camila",
    "Macagni Mariana",
    "Mansilla Rodrigo",
    "Marangio Facundo",
    "Marclay Janice",
    "Matta Mercedes",
    "Matta Dario",
    "Matta Ismael",
    "Matta Rodrigo",
    "Matta Federico",
    "Matta Lorenzo",
    "Matta Joaquin",
    "Matta Loray Geronimo",
    "Matta Loray Valentina",
    "Matta Loray Delfina",
    "Miguez Debora",
    "Mon Lamarca Carola",
    "Montagano Araceli",
    "Montero Nadia",
    "Montero Marcelo",
    "Montero Florencia",
    "Mostovi Valeria",
    "Nicolas Cecilia",
    "Nieto Haydee",
    "Noguerol Joel",
    "Oniszczuk Esteban",
    "Osuna Gloria",
    "Osuna Patricia",
    "Parada Marcelo",
    "Parada Monica",
    "Pedraza Adriana",
    "Polizzi Sandra",
    "Redigo Patricia",
    "Redigo Andrea",
    "Robertson Alan",
    "Rodriguez Daniel",
    "Saffores Gonzalo",
    "Saffores Delfina",
    "Saffores Bautista",
    "Schleser Julieta",
    "Simone Martin",
    "Speranza Javier",
    "Suino Juan",
    "Tomaszeuski Patricio",
    "Vivas Laura"
  ];


export { nombres }